#!/usr/bin/env zsh
autoload -Uz _ZPM_get_plugin_name _ZPM_get_plugin_type _ZPM_get_plugin_basename _ZPM_get_plugin_path _ZPM_get_plugin_link _ZPM_get_plugin_hyperlink _ZPM_get_plugin_root_git_dir

local telemetry=''

# Os 
telemetry+="
# OS Info

| Info | Value |
|---|---|
| OS | $(lsb_release -si -ri -ci) | 
| zsh version | $(zsh --version) | 

"

telemetry+="
# Zpm info

| Info | Value |
|---|---|
|Git branch| $(git symbolic-ref --short HEAD)|
|Git commit| [$(git rev-parse HEAD)](https://github.com/zpm-zsh/zpm/commit/$(git rev-parse HEAD))|

"

telemetry+='
# Plugins 

|Name|Type|Async|Full|
|:--|:--|:--|:--|
'
for i in $_ZPM_plugins_full; do
  local Plugin_name=$(_ZPM_get_plugin_name "$i")
  local Plugin_type=$(_ZPM_get_plugin_type "$i")
  local Plugin_basename=$(_ZPM_get_plugin_basename "$Plugin_name")
  local Plugin_path=$(_ZPM_get_plugin_path "$Plugin_name")
  local Plugin_link=$(_ZPM_get_plugin_link "$Plugin_name" "$Plugin_type")
  local Plugin_hyperlink=$(_ZPM_get_plugin_hyperlink "$Plugin_name" "$Plugin_link")
  local Plugin_git_dir=$(_ZPM_get_plugin_root_git_dir "$Plugin_path" "$Plugin_type")
  
  if [[ "$i" == *",async"* ]]; then
    Plugin_async='true'
  else
    Plugin_async='false'
  fi

  telemetry+="|[${Plugin_name}](${Plugin_link})|${Plugin_type}|${Plugin_async}|${i}|\n"

done

echo $telemetry | md
