#!/usr/bin/env zsh
autoload -Uz _ZPM_get_plugin_name _ZPM_get_plugin_type _ZPM_get_plugin_basename _ZPM_get_plugin_path _ZPM_get_plugin_link _ZPM_get_plugin_hyperlink _ZPM_get_plugin_root_git_dir

_zpm__telemetry_urlencode() (
  # This is important to make sure string manipulation is handled
  # byte-by-byte.
  LC_ALL=C
  str="$1"
  while [ -n "$str" ]; do
    safe="${str%%[!a-zA-Z0-9/:_\.\-\!\'\(\)~]*}"
    printf "%s" "$safe"
    str="${str#"$safe"}"
    if [ -n "$str" ]; then
      printf "%%%02X" "'$str"
      str="${str#?}"
    fi
  done
)


local telemetry=''

# Os 
telemetry+="
# OS Info

| Info | Value |
|---|---|
| OS | $(lsb_release -si -ri -ci) | 
| zsh version | $(zsh --version) | 

"

git_branch=$(git --git-dir="${_ZPM_DIR}/.git/" --work-tree="${_ZPM_DIR}/" symbolic-ref --short HEAD)
git_commit=$(git --git-dir="${_ZPM_DIR}/.git/" --work-tree="${_ZPM_DIR}/" rev-parse HEAD)

telemetry+="
# Zpm info

| Info | Value |
|---|---|
|Git branch|${git_branch}|
|Git commit| [${git_commit}](https://github.com/zpm-zsh/zpm/commit/${git_commit})|

"

telemetry+='
# Plugins 

|Name|Type|Async|Full|
|:--|:--|:--|:--|
'
for i in $_ZPM_plugins_full; do
  local Plugin_name=$(_ZPM_get_plugin_name "$i")
  local Plugin_type=$(_ZPM_get_plugin_type "$i")
  local Plugin_basename=$(_ZPM_get_plugin_basename "$Plugin_name")
  local Plugin_path=$(_ZPM_get_plugin_path "$Plugin_name")
  local Plugin_link=$(_ZPM_get_plugin_link "$Plugin_name" "$Plugin_type")
  local Plugin_hyperlink=$(_ZPM_get_plugin_hyperlink "$Plugin_name" "$Plugin_link")
  local Plugin_git_dir=$(_ZPM_get_plugin_root_git_dir "$Plugin_path" "$Plugin_type")
  
  if [[ "$i" == *",async"* ]]; then
    Plugin_async='true'
  else
    Plugin_async='false'
  fi

  telemetry+="|[${Plugin_name}](${Plugin_link})|${Plugin_type}|${Plugin_async}|${i}|
"

done

telemetry_body_urlencoded=$(_zpm__telemetry_urlencode "$telemetry")
telemetry_title_urlencoded=$(_zpm__telemetry_urlencode "Zpm telemetry")
telemetry_label_urlencoded=$(_zpm__telemetry_urlencode "telemetry")

xdg-open "https://github.com/zpm-zsh/zpm/issues/new?body=${telemetry_body_urlencoded}&title=${telemetry_title_urlencoded}&labels=${telemetry_label_urlencoded}"
