#!/usr/bin/env zsh
#
autoload -Uz \
  @zpm-get-plugin-basename  \
  @zpm-get-plugin-hyperlink \
  @zpm-get-plugin-link      \
  @zpm-get-plugin-name      \
  @zpm-get-plugin-path      \
  @zpm-get-plugin-type      \


function _zpm__telemetry_urlencode() (
  # This is important to make sure string manipulation is handled
  # byte-by-byte.
  LC_ALL=C
  str="$1"
  while [ -n "$str" ]; do
    safe="${str%%[!a-zA-Z0-9/:_\.\-\!\'\(\)~]*}"
    printf "%s" "$safe"
    str="${str#"$safe"}"
    if [ -n "$str" ]; then
      printf "%%%02X" "'$str"
      str="${str#?}"
    fi
  done
)


local telemetry=''

# Os
os_version=$(lsb_release -si -ri -ci)
zsh_version=$(zsh --version)

git_branch=$(git --git-dir="${_ZPM_DIR}/.git/" --work-tree="${_ZPM_DIR}/" symbolic-ref --short HEAD)
git_commit=$(git --git-dir="${_ZPM_DIR}/.git/" --work-tree="${_ZPM_DIR}/" rev-parse HEAD)


telemetry+="
## OS Info

|Info|Value|
|---|---|
|OS|${os_version}|
|zsh version|${zsh_version}|

"

telemetry+="
## Zpm info

|Info|Value|
|---|---|
|Git branch|[${git_branch}](https://github.com/zpm-zsh/zpm/tree/${git_branch})|
|Git commit|[${git_commit}](https://github.com/zpm-zsh/zpm/commit/${git_commit})|

"

telemetry+="
## Plugins

|Name|Type|Async|Options|
|:--|:--|:--|:--|
"

for i in $_ZPM_plugins_full; do
  local Plugin_name=$(@zpm-get-plugin-name "$i")
  local Plugin_type=$(@zpm-get-plugin-type "$Plugin_name")
  local Plugin_basename=$(@zpm-get-plugin-basename "$Plugin_name")
  local Plugin_path=$(@zpm-get-plugin-path "$Plugin_name")
  local Plugin_link=$(@zpm-get-plugin-link "$Plugin_name" "$Plugin_type")
  local Plugin_hyperlink=$(@zpm-get-plugin-hyperlink "$Plugin_name" "$Plugin_link")

  if [[ "$i" == *",async"* ]]; then
    Plugin_async='true'
  else
    Plugin_async='false'
  fi

  if [[ "$i" == *,* ]]; then
     Plugin_option="${${${i}//,async}#*,}"
  else
    Plugin_option=""
  fi


  if [[ "${i%,*}" == "$Plugin_option" ]]; then
    Plugin_option=""
  fi

telemetry+="|[${Plugin_name}](${Plugin_link})|${Plugin_type}|${Plugin_async}|${Plugin_option}|
"

done

telemetry+='
> Telemetry data was generated using [zpm-telemetry](https://github.com/zpm-zsh/zpm-telemetry) extension for [zpm](https://github.com/zpm-zsh/zpm) 😊
'

telemetry_body_urlencoded=$(_zpm__telemetry_urlencode "$telemetry")
telemetry_title_urlencoded=$(_zpm__telemetry_urlencode "Zpm telemetry")
telemetry_label_urlencoded=$(_zpm__telemetry_urlencode "telemetry")

xdg-open "https://github.com/zpm-zsh/zpm-telemetry/issues/new?body=${telemetry_body_urlencoded}&title=${telemetry_title_urlencoded}&labels=${telemetry_label_urlencoded}"
